"""add tipePlat to kendaraan

Revision ID: bc6a1d2e69c4
Revises: 
Create Date: 2026-06-30 12:21:01.038344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc6a1d2e69c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Admin_idAdmin'), 'Admin', ['idAdmin'], unique=False)
    op.add_column('Kendaraan', sa.Column('tipePlat', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Kendaraan_platNomor'), 'Kendaraan', ['platNomor'], unique=False)
    op.alter_column('LogAkses', 'platNomor',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('LogAkses', 'waktuAkses',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_LogAkses_idLog'), 'LogAkses', ['idLog'], unique=False)
    op.create_index(op.f('ix_LogAkses_platNomor'), 'LogAkses', ['platNomor'], unique=False)
    op.create_index(op.f('ix_Personel_idPersonel'), 'Personel', ['idPersonel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Personel_idPersonel'), table_name='Personel')
    op.drop_index(op.f('ix_LogAkses_platNomor'), table_name='LogAkses')
    op.drop_index(op.f('ix_LogAkses_idLog'), table_name='LogAkses')
    op.alter_column('LogAkses', 'waktuAkses',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('LogAkses', 'platNomor',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_index(op.f('ix_Kendaraan_platNomor'), table_name='Kendaraan')
    op.drop_column('Kendaraan', 'tipePlat')
    op.drop_index(op.f('ix_Admin_idAdmin'), table_name='Admin')
    # ### end Alembic commands ###
